name: open_pudo
description: OpenPUDO
publish_to: 'none'
version: 1.0.2+214

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  json_serializable: ^6.0.1
  http: ^0.13.4
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.3
  latlng: ^0.1.0
  location: ^4.3.0
  material_segmented_control: ^3.1.2
  html_unescape: ^2.0.0
  provider: ^6.0.1
  path_provider: ^2.0.6
  shared_preferences: ^2.0.8
  connectivity: ^3.0.6
  flutter_spinkit: ^5.1.0
  flutter_app_badger: ^1.3.0
  notification_permissions: ^0.6.1
  device_info_plus: ^3.1.1
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.12
  firebase_messaging: 10.0.8
  firebase_core: 1.7.0
  flutter_local_notifications: ^9.0.2
  flutter_svg: ^0.23.0+1
  introduction_screen: ^2.1.0
  image: ^3.0.8
  flutter_typeahead: ^3.2.1
  badges: ^2.0.1
  focus_detector: ^2.0.0
  intl: ^0.17.0
  enum_object: ^0.0.2
  pull_to_refresh: ^2.0.0
  geolocator: 7.6.2
  image_picker: ^0.8.4+4
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  logging: ^1.0.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/
   - resources/
 