name: qui_green
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.5+245

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  location: ^4.4.0
  provider: ^6.0.1
  flutter_map: ^2.2.0
  flutter_map_marker_cluster: ^0.5.4
  connectivity_plus: ^2.2.0
  shared_preferences: ^2.0.12
  package_info_plus: ^2.0.0
  latlong2: ^0.8.1
  html_unescape: ^2.0.0
  geolocator: ^9.0.2
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  image_picker: ^0.8.4+11
  flutter_spinkit: ^5.1.0
  retry: ^3.1.0
  simple_shadow: ^0.3.0
  date_format: ^2.0.5
  url_launcher: ^6.0.20
  share_plus: ^5.0.0
  qr_flutter: ^4.0.0
  move_to_background: ^1.0.2
  flutter_qr_bar_scanner: ^3.0.2
  clipboard: ^0.1.3
  firebase_messaging: ^13.1.0
  firebase_analytics: ^9.1.2
  firebase_dynamic_links: ^4.3.5
  firebase_core: ^1.13.1
  flutter_app_badger: ^1.3.0
  device_info_plus: ^6.0.0
  flutter_local_notifications: ^12.0.2
  another_flushbar: ^1.10.28
  stack_trace: ^1.10.0
  focus_detector: ^2.0.1
  transparent_image: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  badges: ^2.0.2
  path_provider: ^2.0.10
  intl_phone_number_input: ^0.7.0+2
  http: ^0.13.5
  http_parser: ^4.0.1
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - resources/
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Italic.ttf
          style: italic
        - asset: fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: fonts/Helvetica-Light.ttf
          weight: 400
        - asset: fonts/Helvetica.ttf
          weight: 600
        - asset: fonts/Helvetica-Thin.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 600
        - asset: fonts/Roboto-Thin.ttf
          weight: 300
